train_data_dir: /vol/unicorn_ssd/projects/ukbb/cardiac/cardiac_segmentations/subjects/
train_start_idx: 0
num_train: 1000
val_data_dir: /vol/unicorn_ssd/projects/ukbb/cardiac/cardiac_segmentations/subjects/
val_start_idx: 1500
num_val: 100
test_data_dir: /vol/unicorn_ssd/projects/ukbb/cardiac/cardiac_segmentations/subjects/
test_start_idx: 1700
num_test: 100
log_dir: /vol/unicorn_ssd/users/zyun/logs/KINS

params:
    # Trainer
    check_val_every_n_epoch: 2
    max_epochs: 500
    early_stopping: False

    # Data
    use_bboxes: False
    cache_data: False
    acceleration: 16

    # Encoder
    enc_embedding: "nerf"
    enc_num_hidden_layers: 4
    enc_att_num_heads: 1
    enc_att_token_size: 128
    enc_hidden_size: 128
    # Decoder
    dec_embedding: "nerf"
    dec_num_hidden_layers: 4
    dec_att_num_heads: 1
    dec_att_token_size: 128
    dec_hidden_size: 128

    # Activation function
    activation: relu  # sine, relu, wire
    # Training
    lr: 1.0e-4
